<?php

use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\field\Entity\FieldConfig;


/**
 * Implementa hook_migrate_pre_row().
 */
function icbf_migrations_migrate_pre_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $settings = $row->getSourceProperty('settings');
  if (is_null($settings)) {
    $row->setSourceProperty('settings', []);
    \Drupal::logger('icbf_migrations')->notice('Entro a icbf_migrations_migrate_pre_row.');
  }

  if ($migration->id() == 'upgrade_d7_field_instance') {
    \Drupal::logger('mymodule')->notice('Normalizando handler_settings[sort] a un array vacío.');
    $settings = $row->getSourceProperty('settings');
    if (!is_array($settings)) {
      $settings = [];
    }
    if (!isset($settings['handler_settings']) || !is_array($settings['handler_settings'])) {
      $settings['handler_settings'] = [];
    }

    if (!isset($settings['handler_settings']['sort']) || !is_array($settings['handler_settings']['sort'])) {
      $settings['handler_settings']['sort'] = [];
      \Drupal::logger('mymodule')->notice('Normalizando handler_settings[sort] a un array vacío.');
    }
    $row->setSourceProperty('settings', $settings);
  }
}

/**
 * Intercepta el preguardado para corregir la configuración del campo de imagen.
 */
function icbf_migrations_entity_presave(EntityInterface $entity) {
  // Verificamos que se trate de una configuración de campo.
  if ($entity instanceof FieldConfig && $entity->getType() === 'image') {
    $settings = $entity->getSettings();

    // Comprobamos si existe la clave 'default_image' y que no sea un array.
    if (isset($settings['default_image']) && !is_array($settings['default_image'])) {
      // Corrigimos el valor asignándole un array por defecto.
      $settings['default_image'] = [
        'uuid' => NULL,
        'fid' => NULL,
        // Se pueden agregar otros valores por defecto según sea necesario.
      ];
      $entity->set('settings', $settings);
      \Drupal::logger('icbf_migrations')->notice('Se corrigió la configuración del campo de imagen: se esperaba un array y se encontró un string.');
    }
  }
}


/**
* Implements hook_migrate_prepare_row().
*/
function icbf_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $source = $row->getSource();
  $instances = $row->getSourceProperty('instances');
  if (isset($source['entity_type']) && $source['entity_type'] == 'comment') {
    $bundle = $row->getSourceProperty('bundle');
    $bundle = substr($bundle, 0, 32);
    $row->setSourceProperty('bundle', $bundle);
  }

  if (is_array($instances) && !empty($instances)) {
    $instance_changed = FALSE;
    foreach ($instances as $key => &$instance) {
      if ($instance['entity_type'] == 'comment') {
        $instance['bundle'] = substr($instance['bundle'], 0, 32);
        $instance_changed = TRUE;
      }
    }
    if ($instance_changed) {
      $row->setSourceProperty('instances', $instances);
    }
  }

  switch ($migration->id()) {
    case 'upgrade_d7_field':
    case 'upgrade_d7_field_instance':
    case 'upgrade_d7_field_instance_widget_settings':
      $type = $row->getSourceProperty('type');
      if ($type == 'text_long' || $type == 'text_with_summary') {
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          if (isset($instance['data'])) {
            $data = unserialize($instance['data']);
            if (isset($data['settings']['text_processing'])) {
              // Set all text processing to filtered text.
              $data['settings']['text_processing'] = 1;

              if (!empty($data['display'])) {
                foreach ($data['display'] as &$display_value) {
                  if ($display_value['type'] == 'text_glazed_builder') {
                    $display_value['type'] = 'text_default';
                    $display_value['module'] = 'text';
                  }
                }
              }

              $instance['data'] = serialize($data);
              $instances[$key] = $instance;
              $row->setSourceProperty('instances', $instances);
            }
          }
        }
      }
      elseif ($type == 'sarnia') {
        return FALSE;
      }
      break;

    case 'upgrade_d7_comment_type':
      if (!$row->getSourceProperty('field_name')) {
        $row->setSourceProperty('field_name', 'comment_body');
      }
      break;

    case 'upgrade_d7_view_modes':
      $entity_type = $row->getSourceProperty('entity_type');
      if ($entity_type == 'sarnia_sarnia') {
        return FALSE;
      }
      elseif ($entity_type == 'bean') {
        $row->setSourceProperty('entity_type', 'block_content');
        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          $instance['entity_type'] = 'block_content';
          $instances[$key] = $instance;
          $row->setSourceProperty('instances', $instances);
        }
      }
      break;

    case 'upgrade_d7_filter_format':
      if ($row->hasSourceProperty('filters')) {
        $filters = $row->getSourceProperty('filters');

        foreach ($filters as &$filter) {
          if (isset($filter['module']) && $filter['module'] === 'ds_format') {
            $filter = [
              'format' => 'php',
              'module' => 'php',
              'name' => 'ds_code',
              'weight' => '0',
              'status' => '1',
              'settings' => [],
            ];
          }
        }
        $row->setSourceProperty('filters', $filters);
      }
      break;

    case 'upgrade_d7_node_complete_webform':
      // Assign default title to Webform nodes.
      if (!$row->hasSourceProperty('title') || empty($row->getSourceProperty('title'))) {
        $row->setSourceProperty('title', 'Webform sin título ' . $row->getSourceProperty('nid'));
      }
      break;

    case 'upgrade_d7_field_formatter_settings':
      $entity_type = $row->getSourceProperty('entity_type');
      $bundle = $row->getSourceProperty('bundle');
      $field_name = $row->getSourceProperty('field_name');
      $type = $row->getSourceProperty('type');
      if ($type == 'text_long' || $type == 'text_with_summary') {

        $instances = $row->getSourceProperty('instances');
        foreach ($instances as $key => $instance) {
          if (isset($instance['data'])) {
            $data = unserialize($instance['data']);
            if (isset($data['settings']['text_processing'])) {
              // Set all text processing to filtered text.
              $data['settings']['text_processing'] = 1;

              if (!empty($data['display'])) {
                foreach ($data['display'] as &$display_value) {
                  if ($display_value['type'] == 'text_glazed_builder') {
                    $display_value['type'] = 'text_default';
                    $display_value['module'] = 'text';
                  }
                }
              }
              $instance['data'] = serialize($data);
              $instances[$key] = $instance;
              $row->setSourceProperty('instances', $instances);

            }
          }
        }
      }
      break;

    case 'upgrade_d7_bean_block':
      if (!$row->getSourceProperty('title')) {
        $label = $row->getSourceProperty('label');
        $row->setSourceProperty('title', $label);
      }
      // dump($source);

      break;
    case 'd7_menu_links':
      if ($source['plid'] == 1741 || $source['plid'] == 50) {
        $row->setSourceProperty('plid', 0);
      }

      if ($row->hasSourceProperty('link_path')) {
        $link_path = $row->getSourceProperty('link_path');

        if (strpos($link_path, 'node/') === 0) {
          $link_path = str_replace('node/', 'internal:/node/', $link_path);
        }
        elseif (strpos($link_path, 'taxonomy/term/') === 0) {
          $link_path = str_replace('taxonomy/term/', 'entity:taxonomy_term/', $link_path);
        }
        elseif (strpos($link_path, 'admin/') === 0) {
          $link_path = str_replace('admin/', 'internal:/admin/', $link_path);
        }
        elseif (strpos($link_path, 'citaciones/') === 0) {
          $link_path = str_replace('citaciones/', 'internal:/citaciones/', $link_path);
        }

        $row->setSourceProperty('link_path', $link_path);
      }
      elseif ($row->hasSourceProperty('parent_link_path')) {
        $link_path = $row->getSourceProperty('parent_link_path');

        if (strpos($link_path, 'admin/') === 0) {
          $link_path = str_replace('admin/', 'internal:/admin/', $link_path);
        }
        $row->setSourceProperty('parent_link_path', $link_path);
      }
      break;
    case 'd7_views_migration':
      $views_id = [
        'usuarios',
        'editorial_last_content',
        'calendario_rendici_n',
        'taxonomy_term',
        'tranpsarencia_listado_temas',
        'glosario_icbf',
        'contexto_micrositios',
        'ada_home_grid',
        'micrositios_contextos',
        'documentos_contratacion',
        'ubicaciones_20',
        'tracker',
        'botones_home',
        'ni_os_migrantes_venezolanos',
        'me_conoces_ni_os_venezolanos',
        'proveedores',
        'media_browser_plus',
        'media_default',
        'informes_regionales_rendici_n_de_cuestas_',
        'sitemap',
        'notificaciones_pc_coactivos',
        'admin_views_node',
        'transparencia_home',
        'actas_contentivas_',
        'estudios_de_sector_v1',
        // 'calendar',
      ];
      if (in_array($source['name'], $views_id)) {
        // dump($source['name']);
        // dump($source);
      }
      else {
        return FALSE;
      }
      break;
  }
}

/**
 * Implements hook_migrate_process_alter().
 *
 * Se ejecuta después de aplicar los plugins de proceso.
 */
function icbf_migrations_migrate_process_alter(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() === 'd7_field_instance') {
    $settings = $row->getSourceProperty('settings');
    if (is_array($settings)) {
      if (isset($settings['handler_settings']) && is_array($settings['handler_settings'])) {
        if (!isset($settings['handler_settings']['sort']) || !is_array($settings['handler_settings']['sort'])) {
          $settings['handler_settings']['sort'] = [];
          $row->setSourceProperty('settings', $settings);
          \Drupal::logger('mimodulo')->notice('hook_migrate_process_alter: forzado settings.handler_settings.sort a array.');
        }
      }
    }
  }
}

/**
 * Implementa hook_views_migration_alter().
 *
 * Permite modificar la definición de migración de vistas.
 */
function icbf_migrations_views_migration_alter(array &$migration) {
  if (isset($migration['id']) && strpos($migration['id'], 'd7_view') !== FALSE) {
    if (!empty($migration['process']['display:default']['filters'])) {
      foreach ($migration['process']['display:default']['filters'] as $key => $filter) {
        if (strpos($key, 'tid') !== FALSE) {
          unset($migration['process']['display:default']['filters'][$key]);
          \Drupal::logger('icbf_migrations')->notice('Filtro de taxonomía eliminado de la migración: ' . $key);
        }
      }
    }
  }
}
